### ISSUE TITLE
CP::Body#m= and #i= should use cpBodySet* functions.

### ISSUE THREAD

**Issue by erisdev** [chipmunk-rb/chipmunk-ffi#1]
I had a look at the code and noticed that you're directly setting the mass and moment values rather than going through the C accessor. In this case, the values in the struct shouldn't be directly modified because the accessors also set m_inv and i_inv to save calculation time for functions that need them.

**Comment by erisdev** [comment]
Just fixed it myself, I think. We'll see.

**Comment by shawn42** [comment]
pulled and merged your fix, thanks!

**Comment by erisdev** [comment]
Glad to help, of course. :)
