### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by shawn42** [chipmunk-rb/chipmunk-ffi#13]
I have downloaded and compiled Chipmunk, but how do I specify the path
for chipmunk-ffi to load? Also, what file should I be loading? Sorry
for the kinda stupid-sounding questions, but I can't seem to figure it
out by looking at the instructions for ffi, and the page for
chipmunk-ffi on github doesn't say either.

**Comment by shawn42** [comment]
chipmunk-ffi uses nice-ffi to load the library.. so depending on your OS you can look here to see the paths:
https://github.com/jacius/nice-ffi/blob/master/lib/nice-ffi/pathset.rb#L567-L591

**Comment by RavensKrag** [comment]
Thanks for the information.  However, I only have libchipmunk.a not libchipmunk.so.  I believe this has something to do with building Chipmunk 5.3.4.  If I build 5.3.1 instead, I do get the libchipmunk.so.

I suppose this means I should just use 5.3.1 for now, but I thought I'd make a note of it.  It seems it's a problem regarding Chipmunk more than your bindings anyway.

**Comment by RavensKrag** [comment]
Problem is confirmed to be with the Chipmunk 5.3.4 code, I assume something in the makefile.

**Comment by slembcke** [comment]
The dynamic library was made optional. You just need to enable it when running cmake:
cmake -D BUILD_SHARED=ON .

**Comment by RavensKrag** [comment]
Thank you for your help, it all seems to be in working order now.

**Comment by shawn42** [comment]
great, thanks slembcke for the help.
