### ISSUE TITLE
massive breakage in 8ec1fddf8971e8b20a2bfbda1b154a936a8fe7fd

### ISSUE THREAD

**Issue by erisdev** [chipmunk-rb/chipmunk-ffi#2]
After merging the changes from 8ec1fddf8971e8b20a2bfbda1b154a936a8fe7fd, I get 38 specs failing, all relating to the newly redefined Vect struct. A cursory glance tells me we are using NiceFFI::Struct#to_bytes pretty extensively to write the Vect struct into other structs' fields, and FFI::Struct has no such method.

**Comment by shawn42** [comment]
erisdiscord fixed
