### ISSUE TITLE
rake fails

### ISSUE THREAD

**Issue by utgarda** [chipmunk-rb/chipmunk-ffi#3]
Hi! :) 
Guess I could use some help with your code.

Here's what I get after just running rake: 

> rake 
> (in /home/etsvigun/devenv/ruby/myforks/chipmunk-ffi)  
> /home/etsvigun/devenv/ruby/myforks/chipmunk-ffi/lib/chipmunk-ffi.rb:1:in `require': no such file to load -- nice-ffi (LoadError)
>         from /home/etsvigun/devenv/ruby/myforks/chipmunk-ffi/lib/chipmunk-ffi.rb:1                                              
>         from ./spec/spec_helper.rb:4:in`require'  
>         from ./spec/spec_helper.rb:4  
>         from ./spec/space_spec.rb:1:in `require'                                                                                
>         from ./spec/space_spec.rb:1                                                                                             
>         from /usr/lib64/ruby/gems/1.8/gems/rspec-1.3.0/lib/spec/runner/example_group_runner.rb:15:in`load'  
>         from /usr/lib64/ruby/gems/1.8/gems/rspec-1.3.0/lib/spec/runner/example_group_runner.rb:15:in `load_files'               
>         from /usr/lib64/ruby/gems/1.8/gems/rspec-1.3.0/lib/spec/runner/example_group_runner.rb:14:in`each'  
>         from /usr/lib64/ruby/gems/1.8/gems/rspec-1.3.0/lib/spec/runner/example_group_runner.rb:14:in `load_files'               
>         from /usr/lib64/ruby/gems/1.8/gems/rspec-1.3.0/lib/spec/runner/options.rb:133:in`run_examples'  
>         from /usr/lib64/ruby/gems/1.8/gems/rspec-1.3.0/lib/spec/runner/command_line.rb:9:in `run'  
>         from /usr/lib64/ruby/gems/1.8/gems/rspec-1.3.0/bin/spec:5  
> rake aborted!  
> Command /usr/bin/ruby -I"lib"  "/usr/lib64/ruby/gems/1.8/gems/rspec-1.3.0/bin/spec" "spec/space_spec.rb" "spec/space_hash_spec.rb" "spec/core_spec.rb" "spec/shape_spec.rb" "spec/constraint_spec.rb" "spec/vec2_spec.rb" "spec/body_spec.rb" "spec/unsafe_spec.rb" "spec/bb_spec.rb"  failed  

I have nice-ffi installed, tried both 1e78ae2f268b2b676d7d1881cb51858a4a27dbe9 and c9b91904209de2e69480d12170a63cf26ae44410. Had to add another line to chipmunk-ffi.rb to get past this. Here : 62d05f48615ce1b5e69a724ad1c62bbe4077bf5d , maybe that's not the best solution.

And, btw, thanks for your code! Most usable chipmunk ruby bindings ever.

**Comment by shawn42** [comment]
Thanks for taking an interest in the chipmunk-ffi bindings.  :)

As for this being a bug.. it's up to the user of the library to decide whether they want rubygems or not.  That can be done in your calling code or in this case -rubygems on the command line or setting your RUBYOPT environment variable.  Maybe I should add it to my own rakefile for development though...

**Comment by utgarda** [comment]
Yep, guess I can handle it on my own now.

**Comment by utgarda** [comment]
Closed.
